export const skills = [
  "Teaching", "Coding", "Designing", "Writing", "Healthcare",
  "Cooking", "Photography", "Music", "Counseling", "Legal Aid",
  "Construction", "Marketing", "Event Planning", "Translation", "Mentoring"
];

export const interests = [
  "Education", "Healthcare", "Environment", "Animal Welfare",
  "Poverty Alleviation", "Women Empowerment", "Child Welfare",
  "Disaster Relief", "Community Development", "Arts & Culture"
];

export const mockEvents = [
  {
    id: "1",
    title: "Community Tree Plantation Drive",
    ngo: "Green Earth Foundation",
    ngoLogo: "🌿",
    description: "Join us for a massive tree plantation drive across the city. Help us plant 1000 trees in a single day!",
    location: "Cubbon Park, Bangalore",
    date: "2026-04-15",
    time: "7:00 AM - 12:00 PM",
    skills: ["Construction", "Event Planning"],
    interests: ["Environment"],
    volunteersNeeded: 50,
    volunteersJoined: 32,
    image: "",
    matchScore: 92,
  },
  {
    id: "2",
    title: "Code for Kids Workshop",
    ngo: "Digital Literacy India",
    ngoLogo: "💻",
    description: "Teach underprivileged children the basics of programming using Scratch and Python.",
    location: "Community Hall, Mumbai",
    date: "2026-04-20",
    time: "10:00 AM - 4:00 PM",
    skills: ["Coding", "Teaching", "Mentoring"],
    interests: ["Education", "Child Welfare"],
    volunteersNeeded: 20,
    volunteersJoined: 14,
    image: "",
    matchScore: 88,
  },
  {
    id: "3",
    title: "Free Health Checkup Camp",
    ngo: "Health For All NGO",
    ngoLogo: "🏥",
    description: "Organize a free health checkup camp in rural areas. Medical professionals and volunteers needed.",
    location: "Village Panchayat, Pune",
    date: "2026-04-25",
    time: "8:00 AM - 5:00 PM",
    skills: ["Healthcare", "Counseling"],
    interests: ["Healthcare", "Poverty Alleviation"],
    volunteersNeeded: 30,
    volunteersJoined: 22,
    image: "",
    matchScore: 75,
  },
  {
    id: "4",
    title: "Art Therapy for Children",
    ngo: "Smile Foundation",
    ngoLogo: "🎨",
    description: "Use art and creativity to help children in orphanages express their emotions and build confidence.",
    location: "Hope Orphanage, Delhi",
    date: "2026-05-01",
    time: "2:00 PM - 6:00 PM",
    skills: ["Designing", "Counseling", "Music"],
    interests: ["Child Welfare", "Arts & Culture"],
    volunteersNeeded: 15,
    volunteersJoined: 8,
    image: "",
    matchScore: 70,
  },
  {
    id: "5",
    title: "Women's Skill Development Program",
    ngo: "Shakti Women's Trust",
    ngoLogo: "👩",
    description: "Help women learn new vocational skills including tailoring, cooking, and digital literacy.",
    location: "Community Center, Hyderabad",
    date: "2026-05-10",
    time: "9:00 AM - 3:00 PM",
    skills: ["Teaching", "Cooking", "Marketing"],
    interests: ["Women Empowerment", "Community Development"],
    volunteersNeeded: 25,
    volunteersJoined: 18,
    image: "",
    matchScore: 65,
  },
  {
    id: "6",
    title: "Beach Cleanup Marathon",
    ngo: "Ocean Warriors",
    ngoLogo: "🌊",
    description: "Join our monthly beach cleanup drive. Together we can protect marine life and keep our beaches clean.",
    location: "Juhu Beach, Mumbai",
    date: "2026-05-15",
    time: "6:00 AM - 10:00 AM",
    skills: ["Event Planning"],
    interests: ["Environment"],
    volunteersNeeded: 100,
    volunteersJoined: 67,
    image: "",
    matchScore: 80,
  },
];

export const mockLeaderboard = [
  { rank: 1, name: "Priya Sharma", hours: 245, badge: "🏆", avatar: "PS", domain: "Education" },
  { rank: 2, name: "Arjun Patel", hours: 210, badge: "🥈", avatar: "AP", domain: "Healthcare" },
  { rank: 3, name: "Sneha Reddy", hours: 198, badge: "🥉", avatar: "SR", domain: "Environment" },
  { rank: 4, name: "Rahul Kumar", hours: 175, avatar: "RK", domain: "Technology" },
  { rank: 5, name: "Ananya Gupta", hours: 162, avatar: "AG", domain: "Child Welfare" },
];

export const mockTestimonials = [
  {
    name: "Meera Iyer",
    role: "Volunteer",
    text: "Soul Bridge connected me with amazing NGOs in my city. I've contributed over 200 hours and earned badges I'm proud of!",
    avatar: "MI",
    rating: 5,
  },
  {
    name: "Green Earth Foundation",
    role: "NGO",
    text: "Finding dedicated volunteers used to take weeks. With Soul Bridge, we get matched with skilled people in days.",
    avatar: "GE",
    rating: 5,
  },
  {
    name: "Vikram Singh",
    role: "Volunteer",
    text: "The smart matching is incredible! Every recommendation perfectly aligns with my skills and interests.",
    avatar: "VS",
    rating: 5,
  },
];

export const mockStats = {
  totalVolunteers: 12500,
  totalNGOs: 450,
  totalHours: 285000,
  totalEvents: 3200,
};

export const mockVolunteerStats = {
  totalHours: 156,
  eventsCompleted: 12,
  badgeCount: 5,
  impactScore: 92,
  weeklyHours: [
    { week: "W1", hours: 8 },
    { week: "W2", hours: 12 },
    { week: "W3", hours: 6 },
    { week: "W4", hours: 15 },
    { week: "W5", hours: 10 },
    { week: "W6", hours: 14 },
    { week: "W7", hours: 18 },
    { week: "W8", hours: 11 },
  ],
  domainBreakdown: [
    { domain: "Education", hours: 45, color: "hsl(174, 60%, 40%)" },
    { domain: "Environment", hours: 35, color: "hsl(30, 80%, 55%)" },
    { domain: "Healthcare", hours: 28, color: "hsl(350, 65%, 58%)" },
    { domain: "Technology", hours: 25, color: "hsl(220, 60%, 50%)" },
    { domain: "Community", hours: 23, color: "hsl(152, 60%, 42%)" },
  ],
  badges: [
    { name: "First Step", icon: "👣", description: "Complete your first event", earned: true },
    { name: "Helping Hand", icon: "🤝", description: "50 hours of volunteering", earned: true },
    { name: "Changemaker", icon: "🌟", description: "100 hours of volunteering", earned: true },
    { name: "Community Hero", icon: "🦸", description: "150 hours of volunteering", earned: true },
    { name: "Legend", icon: "🏆", description: "200 hours of volunteering", earned: false },
    { name: "Multi-Domain", icon: "🎯", description: "Volunteer in 5+ domains", earned: true },
  ],
  upcomingEvents: [
    { title: "Code for Kids Workshop", date: "Apr 20", ngo: "Digital Literacy India" },
    { title: "Beach Cleanup Marathon", date: "May 15", ngo: "Ocean Warriors" },
  ],
};
